version: '3'

networks:
  laravel:
    name: laravel

services:
  nginx:
    build:
      context: .
      dockerfile: docker/local/nginx/nginx.dockerfile
    container_name: nginx
    depends_on:
      - php
      - mysql
      - redis
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html:delegated
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: docker/local/php/php.dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html:delegated
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/local/mysql:/var/lib/mysql:delegated
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/html:delegated
    working_dir: /var/www/html
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: docker/local/php/php.dockerfile
    container_name: artisan
    volumes:
      - .:/var/www/html:delegated
    working_dir: /var/www/html
    entrypoint: [ 'php', 'artisan' ]
    networks:
      - laravel

  phpunit:
    build:
      context: .
      dockerfile: docker/local/php/php.dockerfile
    container_name: phpunit
    volumes:
      - .:/var/www/html:delegated
    working_dir: /var/www/html
    entrypoint: [ "/var/www/html/vendor/bin/phpunit" ]
    networks:
      - laravel

  yarn:
    image: node:current-alpine
    container_name: yarn
    volumes:
      - .:/var/www/html:delegated
    working_dir: /var/www/html
    entrypoint: [ 'yarn' ]
    networks:
      - laravel
